dist: trusty
sudo: required
services:
  - docker
 
# Get Google Chrome headless browser for Angular tests
# Install latest Docker CE so we can use Dockerfile outside build context
addons:
  apt:
#    sources:
#      - google-chrome
    packages:
#     - google-chrome-stable
      - docker-ce
 
# Install any dependencies, update Docker Compose to 1.23.2 so we can use Dockerfile outside build context
before_install:
 - docker --version
 - docker-compose --version
 - sudo rm /usr/local/bin/docker-compose
 - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - docker-compose --version
 
#install:
 
# Build development images for test
before_script:
  - docker build -t j$DOCKER_HUB_ID/apache .

 
# Run some tests
script:
  - docker run -d $DOCKER_HUB_ID/apache  
 
after_success:
 
  # Login to Docker Hub
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push $DOCKER_HUB_ID/apache 

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: apache
  env: apache-env
  bucket_name: elasticbeanstalk-us-east-1-956544467856
  bucket_path: apache
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
